name: Graham Mutter
author: Graham Mutter
baseurl:
description: Code, Fitness, Music
github: http://www.github.com/grahammutter
twitter: http://www.twitter.com/GrahamMutter
email: graham.mutter@gmail.com

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
